### PR TITLE
docs(changelog): update for release 16.5.2

### PR DESCRIPTION
**Pull request by emmenko**
To include the fix from Islam as well

### CODE REVIEW

**Comment by emmenko** [comment]
Already merged (the changelog) #1412

**Comment by emmenko** [comment]
Fuck those node modules

**Comment by emmenko** [comment]
I deleted `node_modules` and `yarn.lock` and re-install all deps but I have no new changes in the `yarn.lock`, besides the ones in this PR. I'm confused...

**Comment by tdeekens** [comment]
I tried many things to resolve the issue internally. Resolutions, compat-data dependency. Nothing really helped 🐼.

**Comment by emmenko** [comment]
If I run `yarn` on `master`, I get a bunch of diff in the `yarn.lock`, like this:

image

Do you also get that?

**Comment by tdeekens** [comment]
Yes. 

CleanShot 2020-03-23 at 17 27 06@2x

**Comment by emmenko** [comment]
Let's see if that helps...

**Pull request merged**
