### PR TITLE
refactor(website): upgrade to theme 1.0.0-canary.28

### PR DESCRIPTION
**Pull request by emmenko**

### CODE REVIEW

**Comment by emmenko** [comment]
@tdeekens any idea why the metrics tests are failing? 🤔

**Comment by emmenko** [comment]
Ah I think I found the issue: we're testing async stuff but the test does not wait for it...for example, I added `await wait` and it works again:

image

**Comment by tdeekens** [comment]
Oh thanks. So it's on the next tick due to fetch I guess.

**Comment by emmenko** [comment]
I suppose...it’s weird though that it comes up now. I’ll open a new PR

**Comment by emmenko** [comment]
Ah s***, I pushed to master directly 🤦‍♂️

https://github.com/commercetools/merchant-center-application-kit/commit/2413741472b86c8ca14e60c7c02a587e54126e18

@tdeekens take a look at the commit anyway please, if you prefer I can revert and open a PR.

**Comment by tdeekens** [comment]
Looks good to me! Thanks.

**Pull request merged**
