### PR TITLE
docs(changelog): v15.3.9 

### PR DESCRIPTION
**Pull request by amine-benselim**

### CODE REVIEW

**Comment by amine-benselim** [comment]
do I `yarn release` after merging this or before? 🤔

**Comment by emmenko** [comment]
First merge, then `yarn release`

**Comment by amine-benselim** [comment]
so skip CI skips the CI, but kodiak is waiting for the CI before merging 🤔

**Comment by amine-benselim** [comment]
> so skip CI skips the CI, but kodiak is waiting for the CI before merging 🤔

@emmenko @tdeekens how do you merge in this case?

**Comment by emmenko** [comment]
Merged, problem solved 😜

**Pull request merged**
