### PR TITLE
WIP - docs(changelog): for v8.1.0 [skip ci]

### PR DESCRIPTION
**Pull request by tdeekens**

### CODE REVIEW

**Comment by tdeekens** [comment]
Sure. It can wait a bit. If it needs too much testing I can release a hot-fix for the QuickAccess-bug if product demands it.

**Comment by emmenko** [comment]
It shouldn't take long, I'll probably release if around lunch time

**Comment by emmenko** [comment]
Waiting for #384 to be merged, then I'll do a release

**Comment by emmenko** [comment]
Closing in favor of #386

**Pull request closed without merging**
