### PR TITLE
Update template for bug issue

### PR DESCRIPTION
**Pull request by Rhotimee**
#### Summary
Update template to prevent duplicate bug issues.

### CODE REVIEW

**Review by CarlosCortizasCT — APPROVED** [review]
Let's hope our users read the new comment 👍 

(_I guess we should do something similar in `ui-kit` repository_)

**Review by emmenko — APPROVED** [review]
Thanks

**Review by kark — APPROVED** [review]
👍 I thought of mentioning [GH discussions](https://github.com/commercetools/merchant-center-application-kit/discussions) as well. Up to you!

**Comment by Rhotimee** [comment]
> Let's hope our users read the new comment 👍
> 
> (_I guess we should do something similar in `ui-kit` repository_)

True, I will add it there as well. 
Thanks.

**Comment by Rhotimee** [comment]
> 👍 I thought of mentioning [GH discussions](https://github.com/commercetools/merchant-center-application-kit/discussions) as well. Up to you!

That makes sense. Updated in commit [de058794d](https://github.com/commercetools/merchant-center-application-kit/pull/2663/commits/de058794d269a27ee8b04c6724034d164ad94b66)

**Review by emmenko — APPROVED** [review]

**Pull request merged**
