### PR TITLE
feat(react-notifications): add OverlappingPriceValidity and OverlappingStandalonePriceValidity error codes

### PR DESCRIPTION
**Pull request by ragafus**
#### Summary

This PR adds two new error codes: OverlappingPriceValidity and OverlappingStandalonePriceValidity that are present in priceless API

### CODE REVIEW

**Review by CarlosCortizasCT — APPROVED** [review]
Looks good to me 👍 

Thanks Rafa!

**Review by kark — APPROVED** [review]
Thanks. Please include a changeset

**Review by dogayuksel — APPROVED** [review]

**Comment by ragafus** [comment]
Blocked until https://github.com/commercetools/sphere-backend/pull/13906 gets merged

**Review by ARRIOLALEO — APPROVED** [review]

**Comment by tomski-ct** [comment]
The [BE PR](https://github.com/commercetools/sphere-backend/pull/13906) has been merged!
🥳

**Pull request merged**
