### PR TITLE
Fix jumpy modal animation on resize

### PR DESCRIPTION
**Pull request by ddouglasz**
#### Summary

Fix issue of jumpy modal animation on page resize

#### Description

Issue: 

https://github.com/commercetools/merchant-center-application-kit/assets/19975842/d2d23fa0-c5c8-418f-b22f-570c9df8d289

Fixed: 

https://github.com/commercetools/merchant-center-application-kit/assets/19975842/83a8f9e2-8ea2-48b5-8845-47127e20ce8c

### CODE REVIEW

**Comment by CarlosCortizasCT** [comment]
Something I noticed with this change is that the open modal animation seems to be different, like the panel is coming from the left instead of the right.

Here is how it looks in the `main` branch:
[App-kit-playground - almond-40 - Merchant Center (2).webm](https://github.com/commercetools/merchant-center-application-kit/assets/97907068/f41d7316-7a20-41a3-9f82-37192075a446)

and here is how it looks in this PR's branch:
[App-kit-playground - almond-40 - Merchant Center (1).webm](https://github.com/commercetools/merchant-center-application-kit/assets/97907068/00173bc3-0bd2-4509-b5e4-69c98d42bfbb)

**Comment by ddouglasz** [comment]
> Something I noticed with this change is that the open modal animation seems to be different, like the panel is coming from the left instead of the right.
> 
> Here is how it looks in the `main` branch: [App-kit-playground - almond-40 - Merchant Center (2).webm](https://github.com/commercetools/merchant-center-application-kit/assets/97907068/f41d7316-7a20-41a3-9f82-37192075a446)
> 
> and here is how it looks in this PR's branch: [App-kit-playground - almond-40 - Merchant Center (1).webm](https://github.com/commercetools/merchant-center-application-kit/assets/97907068/00173bc3-0bd2-4509-b5e4-69c98d42bfbb)

Ah, interesting catch. I am looking into it now. Thank you.

**Comment by chloe0592** [comment]
> Something I noticed with this change is that the open modal animation seems to be different, like the panel is coming from the left instead of the right.
> 
> Here is how it looks in the `main` branch: [App-kit-playground - almond-40 - Merchant Center (2).webm](https://github.com/commercetools/merchant-center-application-kit/assets/97907068/f41d7316-7a20-41a3-9f82-37192075a446)
> 
> and here is how it looks in this PR's branch: [App-kit-playground - almond-40 - Merchant Center (1).webm](https://github.com/commercetools/merchant-center-application-kit/assets/97907068/00173bc3-0bd2-4509-b5e4-69c98d42bfbb)

@CarlosCortizasCT I think we don't need the transition in the `stackingLayer`. It seems to me now it looks as intended. Could you also double check, please? 🦅 

https://github.com/commercetools/merchant-center-application-kit/assets/52276952/793b9a28-d8e5-4fa5-ad49-54b1da28f6f8

**Comment by CarlosCortizasCT** [comment]
Yes, I agree it seems we don't need this change anymore.

I'm closing the PR.

Thanks for looking into it @chloe0592 🙇

**Comment by chloe0592** [comment]
@CarlosCortizasCT we do need this PR since it's fixing the jumpy UI issue when resizing the window. 😄

**Comment by chloe0592** [comment]
I just removed the transition from the `stackingLayer` since it was causing the weird behaviour in multiple modals.

**Review by chloe0592 — APPROVED** [review]

**Review by emmenko — APPROVED** [review]
💯 Thanks

**Pull request merged**
