### PR TITLE
refactor(app-shell): migrate to TS

### PR DESCRIPTION
**Pull request by emmenko**
Ref #589

### CODE REVIEW

**Comment by adnasa** [comment]
shall we follow up on this concern and the discussion that followed before we go head on with TS?

https://github.com/commercetools/merchant-center-application-kit/issues/589#issuecomment-507263984

**Comment by emmenko** [comment]
After 4 months, this is finally ready for merge!! Thanks all for helping out 🙌

**Comment by emmenko** [comment]
FYI: I don't expect any review on this huge PR, all other PRs have been reviewed already. I'll merge this later

**Comment by adnasa** [comment]
I read through this entire thing for a while. I think we are good 🙌

**Pull request merged**
