### PR TITLE
Remove rebranding modal pop-up to announce visual changes

### PR DESCRIPTION
**Pull request by chloe0592**
We no longer need the modal that announced the rebranding changes in the MC.

PR that introduced the modal - [here](https://github.com/commercetools/merchant-center-application-kit/pull/3445).

### CODE REVIEW

**Review by tdeekens — APPROVED** [review]
Awesome. To be frank: I can't wait for this 😄. Let's not forget we can remove some local storage value setting from Cypress and Checkly as a follow-up of integrating this update. Just DM me if you need more information.

**Comment by chloe0592** [comment]
> Awesome. To be frank: I can't wait for this 😄. Let's not forget we can remove some local storage value setting from Cypress and Checkly as a follow-up of integrating this update. Just DM me if you need more information.

Thank you @tdeekens, for the reminder! I removed the local storage values from this repo [here](https://github.com/commercetools/merchant-center-application-kit/pull/3516/commits/f0fc65978517dd3c8153c1c4891566722888ec58). And I'll create a follow-up ticket so we don't miss on removing it from other repos as well.

**Review by kark — APPROVED** [review]
💯

**Review by ddouglasz — APPROVED** [review]
🙌🏾

**Pull request merged**
