### PR TITLE
docs: add release notes for v22

### LINKED ISSUE #3027: Upcoming breaking changes (v22)
```[tasklist]
### Tasks
- [ ] Migrate to Jest v29 https://github.com/commercetools/merchant-center-application-kit/pull/3026
- [ ] Migrate to FormatJS v6 and React Intl v6 https://github.com/commercetools/merchant-center-application-kit/pull/3029
- [ ] Remove Google Analytics tracking https://github.com/commercetools/merchant-center-application-kit/pull/3036
- [ ] Require min Node.js version to be v18 https://github.com/commercetools/merchant-center-application-kit/pull/3039
```

### PR DESCRIPTION
**Pull request by emmenko**
Closes #3027

### CODE REVIEW

**Review by CarlosCortizasCT — APPROVED** [review]
Thanks! 💯

**Review by kark — APPROVED** [review]
🎉

**Review by Rhotimee — APPROVED** [review]
💯

**Comment by Anshuman71** [comment]
@emmenko, the release note contains instructions for migrations. I'll talk with the docs team about how we can better organize this. I suggest we hold on to it till Monday.

**Pull request merged**
