### PR TITLE
fix(babel-preset): refine browser targets

### PR DESCRIPTION
**Pull request by emmenko**
Based on this: https://jamie.build/last-2-versions

image

image

image

### CODE REVIEW

**Review by tdeekens — APPROVED** [review]
Nice. Did you check if the compilation result is different/

**Comment by emmenko** [comment]
No apparent "size" difference

**Review by ddouglasz — APPROVED** [review]
interesting

**Review by CarlosCortizasCT — APPROVED** [review]
👍

**Review by Rhotimee — APPROVED** [review]

**Review by tdeekens — APPROVED** [review]

**Review by chloe0592 — APPROVED** [review]

**Pull request merged**
