### PR TITLE
feat(navbar): add clock with arrow icon to available application icons

### PR DESCRIPTION
**Pull request by stephsprinkle**
#### Summary

- Added clock with arrow icon to available application icons for Change History

Screen Shot 2020-11-17 at 9 49 00 AM

#### Related PR
https://github.com/commercetools/mc-extension-operations/pull/622

### CODE REVIEW

**Review by torihedden — APPROVED** [review]

**Review by nbryant-commercetools — APPROVED** [review]

**Review by tdeekens — APPROVED** [review]

**Review by emmenko — APPROVED** [review]
💅

**Comment by emmenko** [comment]
You have to type it 🙂

https://github.com/commercetools/merchant-center-application-kit/blob/master/%40types/commercetools-uikit__icons/index.d.ts

**Comment by stephsprinkle** [comment]
> You have to type it 🙂
> 
> https://github.com/commercetools/merchant-center-application-kit/blob/master/%40types/commercetools-uikit__icons/index.d.ts

I noticed this as well. Is the typing a manual process? Does it happen in this repo or ui-kit?

**Comment by nbryant-commercetools** [comment]
> You have to type it 🙂
> 
> https://github.com/commercetools/merchant-center-application-kit/blob/master/%40types/commercetools-uikit__icons/index.d.ts

@emmenko ,
Is the process for that documented somewhere?

**Comment by tdeekens** [comment]
> > You have to type it 🙂
> > [https://github.com/commercetools/merchant-center-application-kit/blob/master/%40types/commercetools-uikit__icons/index.d.ts](https://github.com/commercetools/merchant-center-application-kit/blob/master/%40types/commercetools-uikit__icons/index.d.ts?rgh-link-date=2020-11-17T15%3A16%3A15Z)
> 
> @emmenko ,
> Is the process for that documented somewhere?

I don't think so. This happens every 1-2 years and at some point ui-kit will be in TS. I don't think we added much docs here. Feel free to leave some behind if you prefer.

**Review by adnasa — APPROVED** [review]

**Comment by nbryant-commercetools** [comment]
> > > You have to type it 🙂
> > > [https://github.com/commercetools/merchant-center-application-kit/blob/master/%40types/commercetools-uikit__icons/index.d.ts](https://github.com/commercetools/merchant-center-application-kit/blob/master/%40types/commercetools-uikit__icons/index.d.ts?rgh-link-date=2020-11-17T15%3A16%3A15Z)
> > 
> > 
> > @emmenko ,
> > Is the process for that documented somewhere?
> 
> I don't think so. This happens every 1-2 years and at some point ui-kit will be in TS. I don't think we added much docs here. Feel free to leave some behind if you prefer.

@tdeekens ,

Is it a manual process, then, to generate the types or is there currently a script available for that?

**Comment by tdeekens** [comment]
> > > > You have to type it 🙂
> > > > [https://github.com/commercetools/merchant-center-application-kit/blob/master/%40types/commercetools-uikit__icons/index.d.ts](https://github.com/commercetools/merchant-center-application-kit/blob/master/%40types/commercetools-uikit__icons/index.d.ts?rgh-link-date=2020-11-17T15%3A23%3A16Z)
> > > 
> > > 
> > > @emmenko ,
> > > Is the process for that documented somewhere?
> > 
> > 
> > I don't think so. This happens every 1-2 years and at some point ui-kit will be in TS. I don't think we added much docs here. Feel free to leave some behind if you prefer.
> 
> @tdeekens ,
> 
> Is it a manual process, then, to generate the types or is there currently a script available for that?

I don't think so.

**Comment by emmenko** [comment]
It's manual

**Comment by nbryant-commercetools** [comment]
> > @tdeekens ,
> > Is it a manual process, then, to generate the types or is there currently a script available for that?
> 
> I don't think so.

@tdeekens ,
Can you clarify? Is it a manual process?

**Comment by nbryant-commercetools** [comment]
> It's manual

Thanks, @emmenko !

**Comment by tdeekens** [comment]
Yes, it's manual the type definitions are maintained by hand.

**Comment by stephsprinkle** [comment]
Is this ready for the ship it label? I don't have permissions to merge manually.

**Comment by tdeekens** [comment]
Vercel is failing. You can add the label. @emmenko or I will have a look tmr.

**Pull request merged**
