### PR TITLE
feat: add ui-kit to version tracker

### PR DESCRIPTION
**Pull request by montezume**
Same idea is #697

### CODE REVIEW

**Comment by montezume** [comment]
@tdeekens well it's a peer dep though? so we will be sending unknown until it's updated in the apps? 

Am I missing something?

**Comment by montezume** [comment]
Ah, looks like we need to change the approach.

```
/root/merchant-center-application-kit/packages/application-shell/dist/application-shell-index.es.js
Attempted import error: 'version' is not exported from '@commercetools-frontend/ui-kit' (imported as 'version$2').

```

**Comment by emmenko** [comment]
Let's just wait for the next ui-kit release then.

**Comment by montezume** [comment]
@emmenko but then we will crash custom apps right?

**Comment by emmenko** [comment]
What do you mean "we crash custom apps"?

**Comment by tdeekens** [comment]
Yes. That was my concern with this not thinking about custom apps.

**Comment by emmenko** [comment]
You mean because of the peer dependency?

**Comment by emmenko** [comment]
Let's maybe keep this on hold until we release the next appkit major. Then we can bump the peer dependency version.
Also, is there an ETA for the next uikit major?

**Comment by montezume** [comment]
I'll close this for now 😄

**Pull request closed without merging**
