### PR TITLE
chore: use new npm packages @testing-library/*

### PR DESCRIPTION
**Pull request by emmenko**
**DO NOT MERGE YET**

Since the peer dep changed, we should probably mark this as a breaking change. Let's maybe wait for other breaking changes before merging this.

### CODE REVIEW

**Comment by montezume** [comment]
I thought there was a reason why we weren't updating on MC-FE? Because of the breaking change with query now returning an error if there's multiple returns?

**Comment by tdeekens** [comment]
Yeah that‘s why I skipped the update. I felt like the 6-7 changes would break the MC with selectors throwing so we might want to migrate there first?

**Comment by emmenko** [comment]
> Because of the breaking change with query now returning an error if there's multiple returns?

Hmm I wasn't aware of this...can you explain what the problem is?

> It might make more sense to refactor those tests on MC-FE first?

What about the RTL peer dependencies of appkit? Otherwise you end up having 2 versions of RTL, which we should avoid...

**Comment by tdeekens** [comment]
> Hmm I wasn't aware of this...can you explain what the problem is?

As we return rtl from app-kit we would use it in the MC from my knowledge. rtl@7 updates dom-testing-library to v4 which has these. https://github.com/testing-library/dom-testing-library/releases/tag/v4.0.0

**Comment by emmenko** [comment]
Ah ok, then let's close this. Sorry.

**Pull request closed without merging**
