### PR TITLE
refactor(Navbar): new Submenu - part 1

### PR DESCRIPTION
**Pull request by kark**
#### Summary

This PR adds first part of the new Submenu styles. 

**It does not cover the "Tooltip" and the correct positioning of the submenu**.

Screenshot 2023-08-28 at 14 14 32
Screenshot 2023-08-28 at 14 14 43

### CODE REVIEW

**Comment by kark** [comment]
> Nice work @kark 💯, I see the PR already stated not covering the correct position of the submenu but I wanted to point if that also meant for the z-index in cases like these where the submenu is layered together with some modal components?
> 

Thank you Douglas, good point 👍

**Comment by chloe0592** [comment]
@kark thank you for working on it! Nicely done 💪

**Comment by chloe0592** [comment]
Just wanted to mention something when we are already on the topic of `z-index `. But I believe it can be done in a separate PR, not to block this one, if it's not a quick fix.
There's a misplacement of submenus when we have notifications popping out. So that's something we'll need to look into.

Screenshot 2023-08-29 at 08 33 05
Screenshot 2023-08-29 at 08 33 21

**Comment by kark** [comment]
> Just wanted to mention something when we are already on the topic of `z-index `. But I believe it can be done in a separate PR, not to block this one, if it's not a quick fix. There's a misplacement of submenus when we have notifications popping out. So that's something we'll need to look into.
> 
> Screenshot 2023-08-29 at 08 33 05 Screenshot 2023-08-29 at 08 33 21

Thanks, that's a very good point.
I believe it would be more suitable to handle the correct submenu placement in a separate PR since there are many more factors. This PR only applies the submenu styles.

**Review by chloe0592 — APPROVED** [review]

**Review by ddouglasz — APPROVED** [review]
🙏🏾

**Pull request merged**
