### PR TITLE
fix(app-shell): send `teamId` header in Custom Application local development

### PR DESCRIPTION
**Pull request by kark**
#### Summary

Headers after change:

Screenshot 2023-07-18 at 13 12 40

### CODE REVIEW

**Review by CarlosCortizasCT — APPROVED** [review]
Looks good to me, thanks!

Just out of curiosity: what do we need this for?

**Comment by kark** [comment]
> Looks good to me, thanks!
> Just out of curiosity: what do we need this for?

Thanks Carlos, 
this is an essential part of the new flow allowing logging in for non-admins for local development of Custom App.
([ref](https://github.com/commercetools/merchant-center-application-kit/issues/3122))

**Review by tdeekens — APPROVED** [review]

**Review by ddouglasz — APPROVED** [review]
Thank you

**Review by emmenko — APPROVED** [review]
💯

**Pull request merged**
