### PR TITLE
Remove Quick Access feature toggle

### PR DESCRIPTION
**Pull request by dferber90**
🎉 Now that Quick Access is out, we can remove the feature toggle for it.

### CODE REVIEW

**Comment by dferber90** [comment]
@tdeekens Yeah, I was thinking that we could also let this PR sit for a week before merging... but on the other hand, it has worked flawlessly so far. Not sure, we can also play it safe.

**Comment by tdeekens** [comment]
I've talked to the REWE team yesterday and they've used it for weeks and like it. It depends You call. If you add the "On hold" label to this we can wait. Otherwise I'll include it in the release later :)

**Comment by dferber90** [comment]
Let's skip this release then just in case and ship it with the next one (as there were some modifications before we released to respect permissions/feature-toggles which haven't been out there as long). I didn't expect us to release so soon again 🚄

**Comment by dferber90** [comment]
I rebased the branch and I'd be ready to merge this if you're on board 🚢 

cc @emmenko

**Pull request merged**
