### PR TITLE
chore(mc-http-server): update to node v12

### PR DESCRIPTION
**Pull request by tdeekens**
#### Summary

This pull request suggests to update the `mc-http-server` to Node.JS v12.

### CODE REVIEW

**Comment by emmenko** [comment]
What's the reason for it?

**Comment by tdeekens** [comment]
What's the reason against it?

v12 has stuff like: fast `async`/`await`, async stack traves, performance improvements, better http parser.

Dunno. Just felt reasonable to update if there is nothing that speaks against it I suppose.

**Comment by emmenko** [comment]
Sure makes sense. I thought there were some specific reasons.

**Comment by emmenko** [comment]
🤔 why did you close it?

**Comment by tdeekens** [comment]
Oh, I saw your previous comment without the approval as a "lets not do it. these reasons are not specific enough.".

**Comment by emmenko** [comment]
No all good, I just forgot to approve 😅

**Pull request merged**
