### PR TITLE
chore: add cloud identifier for CN prod

### PR DESCRIPTION
**Pull request by Rhotimee**
#### Summary
Add the cloud identifier for China production.

### CODE REVIEW

**Review by CarlosCortizasCT — APPROVED** [review]
👍

**Review by emmenko — COMMENTED** [review]
Thanks!

Please also provide a changeset 😉

**Comment by Anshuman71** [comment]
Great work team!
⚠️ Do not merge! Until the [parent PR](https://github.com/commercetools/commercetools-docs/pull/3300) is ready and merged.

**Comment by Anshuman71** [comment]
@Rhotimee feel free to merge now.

**Pull request merged**
