### PR TITLE
chore: update ui-kit to v5

### PR DESCRIPTION
**Pull request by montezume**
#### Summary

Update ui-kit to version [v5.0.0](https://github.com/commercetools/ui-kit/releases/tag/v5.0.0). App kit isn't affected by the breaking changes. 🎉 🇨🇦 

Decided to make this WIP as the upgrade in the front end is quite involved. Better to get it done there before merging this, or else we will be deploy-blocked.

### CODE REVIEW

**Comment by emmenko** [comment]
@montezume @tdeekens should we also include this in the `v5` release?

**Comment by tdeekens** [comment]
I think so @montezume and @dferber90 should say.

**Comment by montezume** [comment]
yeah why not 🎉

**Comment by emmenko** [comment]
I'm looking into the failing build, because the Table prints a warning (making CI fail)...

**Comment by emmenko** [comment]
Alright, I fixed it 
https://github.com/commercetools/merchant-center-application-kit/pull/199/commits/5226f8b6473e03e66893922022f9dec618ac1635. It's a bit hacky but it does its job for now. This also shows that we need to have a better developer friendlier `<Table>`, as it's also impossible to test it with RTL at the moment.

**Comment by montezume** [comment]
@emmenko just use puppeteer and dom testing library to test it :trollface:

**Pull request merged**
