### PR TITLE
fix(l10n/scripts): fix typo and locale name

### PR DESCRIPTION
**Pull request by mohib0306**
#### Summary

`generate-l10n-data.js` => fix typo in the french locale name and also fix the initial name for the Chinese locale

### CODE REVIEW

**Comment by mohib0306** [comment]
Do we need the changeset for this?

**Comment by emmenko** [comment]
Did you re-run the script?

**Comment by mohib0306** [comment]
Yes, here is the output from the countries section.
```
[country] Updated 6 locales


[country] Data generated with warnings for locale "de".

The field "bq" has changed from "Bonaire, Sint Eustatius und Saba" to "Karibische Niederlande".


[country] Data generated with warnings for locale "es".

The field "ax" has changed from "Islas Åland" to "Islas Aland".
The field "ez" has changed from "zona euro" to "zona del euro".
The field "gg" has changed from "Guernsey" to "Guernesey".


[country] Data generated with warnings for locale "fr-FR".

The field "bn" has changed from "Brunéi Darussalam" to "Brunei".
The field "fm" has changed from "États fédérés de Micronésie" to "Micronésie".
The field "gs" has changed from "Géorgie du Sud et îles Sandwich du Sud" to "Géorgie du Sud-et-les Îles Sandwich du Sud".
The field "hm" has changed from "Îles Heard et McDonald" to "Îles Heard-et-MacDonald".
The field "kg" has changed from "Kirghizistan" to "Kirghizstan".
The field "lr" has changed from "Libéria" to "Liberia".
The field "ng" has changed from "Nigéria" to "Nigeria".
The field "vc" has changed from "Saint-Vincent-et-les-Grenadines" to "Saint-Vincent-et-les Grenadines".
The field "vn" has changed from "Vietnam" to "Viêt Nam".
```

As you can see the `Northern Ireland` data is not changed, meaning the locale mapping is correct.

**Comment by mohib0306** [comment]
`git diff packages/l10n/data/countries`

```
diff --git a/packages/l10n/data/countries/de.json b/packages/l10n/data/countries/de.json
index adb3d0f3..5e5c3ac4 100644
--- a/packages/l10n/data/countries/de.json
+++ b/packages/l10n/data/countries/de.json
@@ -29,7 +29,7 @@
   "bm": "Bermuda",
   "bn": "Brunei Darussalam",
   "bo": "Bolivien",
-  "bq": "Bonaire, Sint Eustatius und Saba",
+  "bq": "Karibische Niederlande",
   "br": "Brasilien",
   "bs": "Bahamas",
   "bt": "Bhutan",
@@ -260,4 +260,4 @@
   "za": "Südafrika",
   "zm": "Sambia",
   "zw": "Simbabwe"
-}
+}
\ No newline at end of file
diff --git a/packages/l10n/data/countries/en.json b/packages/l10n/data/countries/en.json
index 58fe65ab..9329db11 100644
--- a/packages/l10n/data/countries/en.json
+++ b/packages/l10n/data/countries/en.json
@@ -260,4 +260,4 @@
   "za": "South Africa",
   "zm": "Zambia",
   "zw": "Zimbabwe"
-}
+}
\ No newline at end of file
diff --git a/packages/l10n/data/countries/es.json b/packages/l10n/data/countries/es.json
index 88d3353a..27242ae7 100644
--- a/packages/l10n/data/countries/es.json
+++ b/packages/l10n/data/countries/es.json
@@ -14,7 +14,7 @@
   "at": "Austria",
   "au": "Australia",
   "aw": "Aruba",
-  "ax": "Islas Åland",
+  "ax": "Islas Aland",
   "az": "Azerbaiyán",
   "ba": "Bosnia y Herzegovina",
   "bb": "Barbados",
@@ -73,7 +73,7 @@
   "es": "España",
   "et": "Etiopía",
   "eu": "Unión Europea",
-  "ez": "zona euro",
+  "ez": "zona del euro",
   "fi": "Finlandia",
   "fj": "Fiyi",
   "fk": "Islas Malvinas",
@@ -85,7 +85,7 @@
   "gd": "Granada",
   "ge": "Georgia",
   "gf": "Guayana Francesa",
-  "gg": "Guernsey",
+  "gg": "Guernesey",
   "gh": "Ghana",
   "gi": "Gibraltar",
   "gl": "Groenlandia",
@@ -260,4 +260,4 @@
   "za": "Sudáfrica",
   "zm": "Zambia",
   "zw": "Zimbabue"
-}
+}
\ No newline at end of file
diff --git a/packages/l10n/data/countries/fr-FR.json b/packages/l10n/data/countries/fr-FR.json
index 8eeda35b..b8fa85bd 100644
--- a/packages/l10n/data/countries/fr-FR.json
+++ b/packages/l10n/data/countries/fr-FR.json
@@ -27,7 +27,7 @@
   "bj": "Bénin",
   "bl": "Saint-Barthélemy",
   "bm": "Bermudes",
-  "bn": "Brunéi Darussalam",
+  "bn": "Brunei",
   "bo": "Bolivie",
   "bq": "Pays-Bas caribéens",
   "br": "Brésil",
@@ -77,7 +77,7 @@
   "fi": "Finlande",
   "fj": "Fidji",
   "fk": "Îles Malouines",
-  "fm": "États fédérés de Micronésie",
+  "fm": "Micronésie",
   "fo": "Îles Féroé",
   "fr": "France",
   "ga": "Gabon",
@@ -94,13 +94,13 @@
   "gp": "Guadeloupe",
   "gq": "Guinée équatoriale",
   "gr": "Grèce",
-  "gs": "Géorgie du Sud et îles Sandwich du Sud",
+  "gs": "Géorgie du Sud-et-les Îles Sandwich du Sud",
   "gt": "Guatemala",
   "gu": "Guam",
   "gw": "Guinée-Bissau",
   "gy": "Guyana",
   "hk": "R.A.S. chinoise de Hong Kong",
-  "hm": "Îles Heard et McDonald",
+  "hm": "Îles Heard-et-MacDonald",
   "hn": "Honduras",
   "hr": "Croatie",
   "ht": "Haïti",
@@ -121,7 +121,7 @@
   "jo": "Jordanie",
   "jp": "Japon",
   "ke": "Kenya",
-  "kg": "Kirghizistan",
+  "kg": "Kirghizstan",
   "kh": "Cambodge",
   "ki": "Kiribati",
   "km": "Comores",
@@ -136,7 +136,7 @@
   "lc": "Sainte-Lucie",
   "li": "Liechtenstein",
   "lk": "Sri Lanka",
-  "lr": "Libéria",
+  "lr": "Liberia",
   "ls": "Lesotho",
   "lt": "Lituanie",
   "lu": "Luxembourg",
@@ -169,7 +169,7 @@
   "nc": "Nouvelle-Calédonie",
   "ne": "Niger",
   "nf": "Île Norfolk",
-  "ng": "Nigéria",
+  "ng": "Nigeria",
   "ni": "Nicaragua",
   "nl": "Pays-Bas",
   "no": "Norvège",
@@ -243,11 +243,11 @@
   "uy": "Uruguay",
   "uz": "Ouzbékistan",
   "va": "État de la Cité du Vatican",
-  "vc": "Saint-Vincent-et-les-Grenadines",
+  "vc": "Saint-Vincent-et-les Grenadines",
   "ve": "Venezuela",
   "vg": "Îles Vierges britanniques",
   "vi": "Îles Vierges des États-Unis",
-  "vn": "Vietnam",
+  "vn": "Viêt Nam",
   "vu": "Vanuatu",
   "wf": "Wallis-et-Futuna",
   "ws": "Samoa",
@@ -260,4 +260,4 @@
   "za": "Afrique du Sud",
   "zm": "Zambie",
   "zw": "Zimbabwe"
-}
+}
\ No newline at end of file
diff --git a/packages/l10n/data/countries/ja.json b/packages/l10n/data/countries/ja.json
index bb9eea02..b6f0824a 100644
--- a/packages/l10n/data/countries/ja.json
+++ b/packages/l10n/data/countries/ja.json
@@ -260,4 +260,4 @@
   "za": "南アフリカ",
   "zm": "ザンビア",
   "zw": "ジンバブエ"
-}
+}
\ No newline at end of file
diff --git a/packages/l10n/data/countries/zh-CN.json b/packages/l10n/data/countries/zh-CN.json
index 4e7ee5f5..42a874bd 100644
--- a/packages/l10n/data/countries/zh-CN.json
+++ b/packages/l10n/data/countries/zh-CN.json
@@ -260,4 +260,4 @@
   "za": "南非",
   "zm": "赞比亚",
   "zw": "津巴布韦"
-}
+}
\ No newline at end of file

```

**Review by emmenko — APPROVED** [review]
Thanks!

**Pull request merged**
