### PR TITLE
refactor: to add `includeSubDomains` directive to STS header

### PR DESCRIPTION
**Pull request by emmenko**
Just moving this from the proxy router config, to avoid duplication.

### CODE REVIEW

**Review by tdeekens — APPROVED** [review]
Hm. Thought we had this before. Must have gotten lost.

**Comment by emmenko** [comment]
> Hm. Thought we had this before. Must have gotten lost.

We have it internally and wanted to move it to appkit (but forgot to do so) 😅

image

**Review by CarlosCortizasCT — APPROVED** [review]

**Comment by CarlosCortizasCT** [comment]
Just to double check: so we will have a follow-up PR in MC gateway to remove this header management?

**Comment by emmenko** [comment]
Yes

**Review by Rhotimee — APPROVED** [review]

**Pull request merged**
