### PR TITLE
[experiment] Try Roboto font-family

### PR DESCRIPTION
**Pull request by montezume**
####

!not to merge

I need to do a beta release so that Sven can test this in the MC

Found a bug in UI Kit

https://github.com/commercetools/ui-kit/pull/1061

### CODE REVIEW

**Comment by montezume** [comment]
@emmenko so I'm assuming the best way to test this in the MC is to make a beta release here, and then make a deployed branch in MC using this beta release?

**Comment by emmenko** [comment]
PS: the ui-kit upgrade can be moved to a separate PR

**Comment by montezume** [comment]
yeah, I need the UI Kit update in here as well though, because it contains the removal of Open Sans in the SelectInputs

**Comment by montezume** [comment]
Going to close this as I've made the deploy link.

**Pull request closed without merging**
