### PR TITLE
feat(application-shell): add user business role custom dimension tracking 

### PR DESCRIPTION
**Pull request by fuchodeveloper**
#### Summary

add user business role custom dimension tracking 

#### Description

We want to always have the user business role custom dimensions information available when the application loads like we do for the application name and project key custom dimensions.

### CODE REVIEW

**Review by emmenko — CHANGES_REQUESTED** [review]
Thanks.

You also have to pass the actual value to the component though: https://github.com/commercetools/merchant-center-application-kit/blob/06c563190f354e9544ef0792e3f072826624472b/packages/application-shell/src/components/application-shell/application-shell.tsx#L245-L248

PS: can you also add a changeset?

**Review by emmenko — APPROVED** [review]
Thanks 👌

**Review by tdeekens — APPROVED** [review]

**Review by islam3zzat — APPROVED** [review]

**Comment by fuchodeveloper** [comment]
@commercetools/shield-team-fe 
Tagging for a review as this blocks [another ticket](https://jira.commercetools.com/browse/PRC-1363).

**Comment by tdeekens** [comment]
@fuchodeveloper I think it was sufficiently reviewed. @emmenko is part of the team. Feel free to merge.

**Comment by fuchodeveloper** [comment]
> @fuchodeveloper I think it was sufficiently reviewed. @emmenko is part of the team. Feel free to merge.

merging is blocked:
```
 cannot merge (reviews requested: ['dogayuksel', 'Shield team (FE)'])
```

**Comment by islam3zzat** [comment]
> merging is blocked:

You can remove the un-decided requests, to let the bot do its magic :)

**Pull request merged**
