### PR TITLE
refactor(release): publish canary using changeset snapshot feature

### PR DESCRIPTION
**Pull request by emmenko**
The new shapshot feature got released recently. I tried that in a personal project and it works.

### CODE REVIEW

**Comment by emmenko** [comment]
For publishing yes. We still use Lerna CLI to run some useful “multi-package” commands, which are not possible with `yarn workspaces`.

**Comment by tdeekens** [comment]
Hm. There is yarn workspaces run now. Would that help? https://yarnpkg.com/lang/en/docs/cli/workspaces/

**Comment by emmenko** [comment]
Options like `--no-private` is what I'm missing at the moment.

**Comment by tdeekens** [comment]
Too bad 😋. Thanks for checking.

**Pull request merged**
