### PR TITLE
Update renovate.json

### PR DESCRIPTION
**Pull request by tdeekens**
#### Summary

I wondered the other day if we could tell Renovate to stop updating certain PRs as we plan to work on e.g. that major dependency update in the future. This can save us some CI cost and needless timeline entries on the affected PRs.

Turns it Renovate can do that https://docs.renovatebot.com/configuration-options/#stopupdatinglabel

### CODE REVIEW

**Review by CarlosCortizasCT — APPROVED** [review]
💯 
Thanks!

**Review by emmenko — APPROVED** [review]
Nice 🤩

**Comment by tdeekens** [comment]
@emmenko any idea why it fails?

**Comment by emmenko** [comment]
This should fix it: https://github.com/commercetools/merchant-center-application-kit/pull/2966/commits/21961d97b08c63ec7d62483bccfda38b2e789be8

No idea how this has been working so far 🙃

**Pull request merged**
