### PR TITLE
refactor(quick-access): leftover for permissions cleanup

### PR DESCRIPTION
**Pull request by emmenko**
Leftovers from #842

### CODE REVIEW

**Comment by tdeekens** [comment]
Thanks. Will include. I personally don't really like having the fns for one and multiple with the only difference accepting an array or not. Anyway. Thanks :)

**Comment by emmenko** [comment]
> I personally don't really like having the fns for one and multiple with the only difference accepting an array or not

Yeah, actually we only use `hasPermission` in quick-access, we don't use it in the MC. Should we remove the export from the `permissions` package (in v14)?

```js
export {
  hasPermission,
  hasEveryPermissions,
  hasSomePermissions,
} from './utils/has-permissions';
```

**Comment by tdeekens** [comment]
> Yeah, actually we only use hasPermission in quick-access, we don't use it in the MC. Should we remove the export from the permissions package (in v14)?

Yeah I wouldn't mind removing it. But then we'd to refactor the usages again to `hasSomePermission` in QuickAccess?

**Comment by emmenko** [comment]
> But then we'd to refactor the usages again to hasSomePermission in QuickAccess?

Yes, we can also do that in the v14 branch.

**Pull request merged**
