### PR TITLE
chore: unrevert contexts for app-components storybook.

### PR DESCRIPTION
**Pull request by montezume**
Updated to storybook 5.1.5, and unreverted the contexts upgrade.

### CODE REVIEW

**Comment by emmenko** [comment]
Although now that we can potentially test the components within the website, I was thinking of dropping storybook.

**Comment by tdeekens** [comment]
> Although now that we can potentially test the components within the website, I was thinking of dropping storybook.

I would suggest to drop it once the website goes live.

**Comment by emmenko** [comment]
> I would suggest to drop it once the website goes live.

I personally never had a need to use it, because I can just use the website to test it. Design also does not need it anymore.
@jonnybel what do you think?

If we don't need it I'd rather just drop it now (less maintenance work)

**Comment by montezume** [comment]
If it's not needed for the development of new components I also say we should drop it. However, going back to this PR, is there a way in the website to test the component under different locales 🤔 ?

**Comment by jonnybel** [comment]
I also don't see the need for keeping storybook anymore, since it's not deployed and we can now test the components on the website.

**Comment by emmenko** [comment]
Cool, then I'll open a PR to drop storybook

>  is there a way in the website to test the component under different locales

We can add it in the "playground" mode, with the knobs

**Comment by emmenko** [comment]
Here you go: https://github.com/commercetools/merchant-center-application-kit/pull/744

**Pull request merged**
