### PR TITLE
Adding export proxy target

### PR DESCRIPTION
**Pull request by MicheleRezk**
Adding export proxy target as a new MC API target

### CODE REVIEW

**Comment by emmenko** [comment]
Thanks. Please also add a changeset 🤗

**Comment by emmenko** [comment]
Just checking: is the `/proxy/export` endpoint already available on production in the MC API?

**Comment by MicheleRezk** [comment]
No it's available only on the staging right now

**Comment by emmenko** [comment]
Ok then we shouldn't merge this until it's on production.

You can still manually specify the target in your code, the constant is just a nice-to-have thing 🤗

**Comment by yassinejebli** [comment]
@emmenko Can we merge this PR?

**Comment by yassinejebli** [comment]
I just asked my team if `/proxy/export` is deployed on prod, I will let you know when I get a reply.

**Review by emmenko — APPROVED** [review]

**Comment by emmenko** [comment]
@yassinejebli Can you do a rebase of this PR and mark it ready for review? Thanks

**Comment by yassinejebli** [comment]
It turned out the endpoint is only available on the [staging](https://github.com/commercetools/merchant-center-services/blob/main/k8s/values/ctp-gcp-production-eu/merchant-center-backend/values.yaml), I think I will just set the proxy target manually for now :)

**Comment by emmenko** [comment]
Closing as stale. Feel free to reopen if needed.

**Pull request closed without merging**
