### PR TITLE
fix(public-page-layout): allow container to flex beyond 100vh

### PR DESCRIPTION
**Pull request by dogayuksel**
#### Summary

| Before | After |
| - | - |
| before | after |

#### Description

Modify styles to allow container to flex beyond 100vh when there is enough content that overflows the viewport.

### CODE REVIEW

**Review by tdeekens — APPROVED** [review]

**Comment by tdeekens** [comment]
Looks good. Don't forget to add a changeset for the release :)

**Review by adnasa — APPROVED** [review]

**Comment by adnasa** [comment]
oh crap, I was too eager to merge this without the changeset in place.
sorry about that, @dogayuksel 
What we can do is simply open a new PR where the changeset is pushed, no worries

**Review by emmenko — COMMENTED** [review]
Ah thanks for that!

**Comment by emmenko** [comment]
The changeset is missing btw, otherwise this won't get released.

**Comment by tdeekens** [comment]
It's not like I didn't mention it ;)

**Comment by adnasa** [comment]
I fucked up. but let's open a new PR.

**Comment by emmenko** [comment]
It's fine, we're just teasing you 🤓

**Pull request merged**
